version: '3.7'

services:

  postgresd:
    image: postgres:9.6
    ports:
      - "5432:5432"
    volumes:
      - ./docker-volumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=ory
      - POSTGRES_PASSWORD=ory
      - POSTGRES_DB=postgres
    networks:
      - ory

  sqlserver:
    # image: samuelmarks/mssql-server-fts-sqlpackage-linux
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: Ory-MsSqlServer
    environment:
     - ACCEPT_EULA=Y
     - SA_PASSWORD=Rotring123_
    ports:
     - "1433:1433"
    volumes:
     - ./docker-volumes/mssql:/var/opt/mssql
    networks:
      - ory

networks:
  ory:
    name: ory
