version: '3.7'

services:
####################################### KRATOS #######################################################################
  kratos-migrate:
    container_name: kratos-migrate
    image: oryd/kratos:v0.8.0-alpha.3
    environment:
      - DSN=postgres://ory:ory@postgresd:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - type: volume
        source: kratos-db
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./contrib/quickstart/kratos/email-password
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - ory
  kratos:
    container_name: kratos
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.8.0-alpha.3
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      - DSN=postgres://ory:ory@postgresd:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=trace
      # - SERVE_PUBLIC_BASE_URL=http://127.0.0.1:4433/
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: volume
        source: kratos-db
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./contrib/quickstart/kratos/email-password
        target: /etc/config/kratos
    networks:
      - ory

####################################### END KRATOS #######################################################################
####################################### UI #######################################################################
  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v0.8.0-alpha.3
    environment:
      - PORT=4435 # Why is this important? In `access-rules.yml` is configured that request is redirected to this port
      - KRATOS_BROWSER_URL=http://127.0.0.1:4433
      # - JWKS_URL=http://oathkeeper:4456/.well-known/jwks.json
      - SECURITY_MODE=jwks
      - KRATOS_PUBLIC_URL=http://kratos:4433/
    ports:
      - "4435:4435"
    networks:
      - ory
    restart: on-failure
####################################### END UI #######################################################################
####################################### TOOLS #######################################################################
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
    networks:
      - ory

####################################### END TOOLS #######################################################################
####################################### OAuth Keeper #######################################################################
  oathkeeper:
    image: oryd/oathkeeper:v0.38
    depends_on:
      - kratos
    ports:
      - 4455:4455
      - 4456:4456
      - 1234:5291
    command:
      serve proxy -c "/etc/config/oathkeeper/oathkeeper.yml"
    environment:
      - LOG_LEVEL=debug
    restart: on-failure
    networks:
      - ory
    volumes:
      - ./contrib/quickstart/oathkeeper:/etc/config/oathkeeper
####################################### END OAuth Keeper #######################################################################
####################################### HYDRA #######################################################################
  hydra:
    container_name: hydra
    image: oryd/hydra:v1.11.1
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
      - "5555:5555" # Port for hydra token user
    command:
      serve -c /etc/config/hydra/hydra.yml all --dangerous-force-http
    volumes:
      -
        type: volume
        source: hydra-db
        target: /var/lib/sqlite
        read_only: false
      -
        type: bind
        source: ./contrib/quickstart/hydra
        target: /etc/config/hydra
    environment:
      - DSN=postgres://ory:ory@postgresd:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
    restart: unless-stopped
    depends_on:
      - hydra-migrate
    networks:
      - ory

  hydra-migrate:
    container_name: hydra-migrate
    image: oryd/hydra:v1.11.1
    environment:
      - DSN=postgres://ory:ory@postgresd:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
    command:
      migrate -c /etc/config/hydra/hydra.yml sql -e --yes
    volumes:
      -
        type: volume
        source: hydra-db
        target: /var/lib/sqlite
        read_only: false
      -
        type: bind
        source: ./contrib/quickstart/hydra
        target: /etc/config/hydra
    restart: on-failure
    networks:
      - ory
####################################### END HYDRA #######################################################################
####################################### API #######################################################################
  api:
    # build: ./api
    image: ory-api:latest
    ports:
      - 5291:80
    networks:
      - ory
####################################### END API #######################################################################
####################################### TalentLyft Auth #######################################################################
  # tl-atuh:
  #   image: ory-tl-auth:latest
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Staging
  #     - DataProtectionStorageCS="https://adoptostaging.blob.core.windows.net/key-container/keys.xml?sv=2019-10-10&ss=b&srt=o&sp=rwdcx&se=2050-06-11T22:00:13Z&st=2020-06-11T11:00:13Z&spr=https&sig=Jpj6tFAiE2%2B%2B01d9tZ7jxRG1XRwmWhI1SUmIO8RO2%2Bs%3D"
  #   ports:
  #     - 5250:80
  #     - 5251:442
  #   networks:
  #     - ory
####################################### END TalentLyft Auth #######################################################################
networks:
  ory:
    name: ory

volumes:
  kratos-db:
  hydra-db:
